version: '3'

services:
  auth:
    build: .
    ports:
      - 4001:${PORT}
    depends_on:
     - redis
    environment:
      - MONGO_URL=${DATABASE_URL}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

    networks:
      - mas-hms-network

  redis:
    image: redis:alpine
    ports:
      - 6381:6379
    volumes:
      - redis-data:/data
    networks:
      - mas-hms-network

volumes:
  redis-data:

networks:
  mas-hms-network:
    external: true
