version: '3'

services:
  app:
    container_name: hms-auth-service
    build: .
      
    ports:
      - 4001:4001
   
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URL= ${DATABASE_URL}
    volumes:
      - .:/usr/src/app
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
